apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-dynamo-app
  namespace: argocd  # Ensure this matches your ArgoCD namespace
spec:
  project: default
  source:
    repoURL: https://github.com/ambatibhargavi/argo-db  # Replace with your repo URL
    targetRevision: main  
    path: manifests  
  destination:
    server: https://kubernetes.default.svc  
    namespace: default  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
