apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dynamo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-dynamo
  template:
    metadata:
      labels:
        app: flask-dynamo
    spec:
      containers:
      - name: my-app
        image: bharu2003/my-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-dynamo-service
spec:
  selector:
    app: flask-dynamo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
